user:
  email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
  max_name_length: 50
  max_email_length: 255
  min_password_length: 6

micropost:
  max_content_length: 140
  digit_50: 50

image:
  width: 500
  height: 500
  size_5: 5

pagy:
  page_10: 10

gravatar:
  size_80: 80
  size_50: 50

time:
  hour:
    two: 2
